# Generated by Django 5.2.9 on 2026-01-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_homepage_og_image_square"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagecarditem",
            name="tagline",
        ),
        migrations.AlterField(
            model_name="homepagecarditem",
            name="heading",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
