# Generated by Django 5.2.9 on 2026-01-18 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_homepagecarditem_tagline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="non_member_blurb",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="non_member_headline",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="non_member_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="non_member_link_page",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="non_member_link_text",
        ),
    ]
