# Generated by Django 5.2.9 on 2026-01-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0042_articlelistpage_og_image_square_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inducteedetailpage",
            name="inducted_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
