# Generated by Django 5.2.9 on 2026-02-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0044_inducteeoutboundlinksection_inducteeoutboundlink"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inducteeoutboundlink",
            options={},
        ),
        migrations.AlterField(
            model_name="inducteeoutboundlink",
            name="downloaded_datetime",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="inducteeoutboundlink",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="inducteeoutboundlinksection",
            name="title",
            field=models.CharField(
                blank=True, help_text="Section Heading", max_length=250
            ),
        ),
        migrations.AddConstraint(
            model_name="inducteeoutboundlink",
            constraint=models.UniqueConstraint(
                fields=("section", "url"), name="unique_page_url_link"
            ),
        ),
    ]
