# Generated by Django 5.2.9 on 2026-02-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0045_alter_inducteeoutboundlink_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inducteeoutboundlink",
            name="domain",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
