# Generated by Django 5.2.9 on 2026-02-06 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0046_inducteeoutboundlink_domain"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inducteeoutboundlink",
            options={"ordering": ["sort_order"]},
        ),
    ]
