# Generated by Django 5.2.11 on 2026-04-13 03:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0047_alter_inducteeoutboundlink_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("blockquote", 4),
                    ("editorsnote", 6),
                    ("html", 7),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ol",
                                "ul",
                                "hr",
                                "image",
                                "embed",
                                "code",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "blockquote",
                                "text-highlight",
                            ]
                        },
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Quote", "required": True},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("quote", 3)]], {}),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Editor's Note", "required": True},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("note", 5)]], {}),
                    7: ("wagtail.blocks.RawHTMLBlock", (), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="freeformpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2), ("html", 3)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.RawHTMLBlock", (), {}),
                },
            ),
        ),
    ]
