# Generated by Django 5.2.9 on 2026-02-06 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0007_magazineissuepage_og_image_square_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazinepage",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="magazine.magazineissuepage",
            ),
        ),
    ]
