# Generated by Django 5.2.9 on 2026-02-06 21:17

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0009_magazinesearchpage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="magazinepage",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["text"], name="magazine_page_text", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
