# Generated by Django 5.2.9 on 2026-02-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0010_magazinepage_magazine_page_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazineissuepage",
            name="date",
            field=models.DateField(
                db_index=True,
                help_text="Date of issue for this magazine release. Used for sorting issues by date.",
            ),
        ),
    ]
