# Generated by Django 5.2.9 on 2026-02-07 00:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0011_alter_magazineissuepage_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="magazinepage",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("text", config="english"),
                name="mg_page_search_vector_idx",
            ),
        ),
    ]
