# Generated by Django 5.2.9 on 2026-02-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0012_magazinepage_mg_page_search_vector_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazineissuepage",
            name="ai_processed_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="magazinepage",
            name="ai_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="magazinepage",
            name="ai_title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
