# Generated by Django 5.2.9 on 2026-02-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0013_magazineissuepage_ai_processed_datetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="magazinepage",
            old_name="ai_title",
            new_name="ai_page_title",
        ),
        migrations.RenameField(
            model_name="magazinepage",
            old_name="ai_summary",
            new_name="ai_story_summary",
        ),
        migrations.AddField(
            model_name="magazineissuepage",
            name="ai_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="magazinepage",
            name="ai_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="magazinepage",
            name="ai_story_author",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="magazinepage",
            name="ai_story_title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
