# Generated by Django 5.2.9 on 2026-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0014_rename_ai_title_magazinepage_ai_page_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazinepage",
            name="ai_story_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
