# Generated by Django 5.2.11 on 2026-04-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0015_alter_magazinepage_ai_story_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazineissuepage",
            name="ai_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
