# Generated by Django 5.2.11 on 2026-02-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0015_alter_magazinepage_ai_story_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazinepage",
            name="story_author",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="magazinepage",
            name="story_title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
