# Generated by Django 5.2.11 on 2026-02-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0016_magazinepage_story_author_magazinepage_story_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazinepage",
            name="story_title",
            field=models.CharField(
                blank=True, db_index=True, max_length=250, null=True
            ),
        ),
    ]
