# Generated by Django 5.2.11 on 2026-02-18 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0047_alter_inducteeoutboundlink_options"),
        ("magazine", "0017_alter_magazinepage_story_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazinepage",
            name="story_article_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="magazine_pages",
                to="content.articlepage",
            ),
        ),
    ]
