# Generated by Django 5.2.11 on 2026-02-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0018_magazinepage_story_article_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazinepage",
            name="story_heading",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
